"""init

Revision ID: 01a294fe9474
Revises: 
Create Date: 2026-08-22 15:37:18.931114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01a294fe9474'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corporation', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('hazard_type', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_corporation'), 'events', ['corporation'], unique=False)
    op.create_table('field_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_id', sa.String(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('corporation', sa.String(), nullable=True),
    sa.Column('raw_corporation', sa.String(), nullable=True),
    sa.Column('community', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('incident_type', sa.String(), nullable=True),
    sa.Column('raw_incident_type', sa.String(), nullable=True),
    sa.Column('incident_type_other', sa.String(), nullable=True),
    sa.Column('incident_summary', sa.Text(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('event_time', sa.String(), nullable=True),
    sa.Column('assessment_date', sa.DateTime(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('edit_date', sa.DateTime(), nullable=True),
    sa.Column('occupants_count', sa.Integer(), nullable=True),
    sa.Column('injuries_occurred', sa.Boolean(), nullable=False),
    sa.Column('injuries_count', sa.Integer(), nullable=True),
    sa.Column('deaths_occurred', sa.Boolean(), nullable=False),
    sa.Column('deaths_count', sa.Integer(), nullable=True),
    sa.Column('building_damage', sa.Text(), nullable=True),
    sa.Column('crops_livestock', sa.Text(), nullable=True),
    sa.Column('personal_items', sa.Text(), nullable=True),
    sa.Column('furniture_appliances', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.String(), nullable=True),
    sa.Column('relief_items', sa.Text(), nullable=True),
    sa.Column('shelter', sa.Text(), nullable=True),
    sa.Column('special_needs_occupants', sa.Integer(), nullable=True),
    sa.Column('estimated_damage_cost', sa.Numeric(), nullable=True),
    sa.Column('follow_up', sa.String(), nullable=True),
    sa.Column('follow_up_flags', sa.JSON(), nullable=False),
    sa.Column('validation_status', sa.String(), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('duplicate_reason', sa.String(), nullable=True),
    sa.Column('flood_type', sa.String(), nullable=True),
    sa.Column('flood_trigger', sa.String(), nullable=True),
    sa.Column('flood_height', sa.String(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('dedup_hash', sa.String(), nullable=True),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_observations_dedup_hash'), 'field_observations', ['dedup_hash'], unique=False)
    op.create_index(op.f('ix_field_observations_global_id'), 'field_observations', ['global_id'], unique=True)
    op.create_table('report_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('data_requirements', sa.JSON(), nullable=False),
    sa.Column('narration', sa.JSON(), nullable=False),
    sa.Column('render', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_report_templates_name_version')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('template', sa.String(), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('data_requirements', sa.JSON(), nullable=False),
    sa.Column('fact_table', sa.JSON(), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('violations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('whatsapp_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('as_at', sa.DateTime(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('pii_redacted', sa.Boolean(), nullable=False),
    sa.Column('incidents', sa.JSON(), nullable=False),
    sa.Column('logs', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corporation', sa.String(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('as_at', sa.DateTime(), nullable=False),
    sa.Column('alert_level', sa.String(), nullable=False),
    sa.Column('present_activity', sa.Text(), nullable=True),
    sa.Column('situation_overview', sa.Text(), nullable=True),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('row_errors', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corporation', 'event_id', 'sequence_no', name='uq_submission_corp_event_sequence')
    )
    op.create_index(op.f('ix_submissions_as_at'), 'submissions', ['as_at'], unique=False)
    op.create_index(op.f('ix_submissions_corporation'), 'submissions', ['corporation'], unique=False)
    op.create_index(op.f('ix_submissions_event_id'), 'submissions', ['event_id'], unique=False)
    op.create_table('capture_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corporation', sa.String(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('as_at', sa.DateTime(), nullable=False),
    sa.Column('alert_level', sa.String(), nullable=False),
    sa.Column('present_activity', sa.Text(), nullable=True),
    sa.Column('situation_overview', sa.Text(), nullable=True),
    sa.Column('incidents', sa.JSON(), nullable=False),
    sa.Column('logs', sa.JSON(), nullable=False),
    sa.Column('manual_fields', sa.JSON(), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('report_id', sa.String(), nullable=True),
    sa.Column('sitrep_markdown', sa.Text(), nullable=True),
    sa.Column('sitrep_fact_table', sa.JSON(), nullable=True),
    sa.Column('sitrep_violations', sa.JSON(), nullable=True),
    sa.Column('sitrep_status', sa.String(), nullable=True),
    sa.Column('sitrep_generated_at', sa.DateTime(), nullable=True),
    sa.Column('sitrep_source_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name='fk_capture_sessions_report_id'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capture_sessions_corporation'), 'capture_sessions', ['corporation'], unique=False)
    op.create_index(op.f('ix_capture_sessions_event_id'), 'capture_sessions', ['event_id'], unique=False)
    op.create_table('sitrep_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('corporation', sa.String(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('row_id', sa.String(), nullable=False),
    sa.Column('community', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('incident_type', sa.String(), nullable=True),
    sa.Column('raw_incident_type', sa.String(), nullable=True),
    sa.Column('incident_summary', sa.Text(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('injuries_occurred', sa.Boolean(), nullable=False),
    sa.Column('injuries_count', sa.Integer(), nullable=True),
    sa.Column('deaths_occurred', sa.Boolean(), nullable=False),
    sa.Column('deaths_count', sa.Integer(), nullable=True),
    sa.Column('building_damage', sa.Text(), nullable=True),
    sa.Column('special_needs_occupants', sa.Integer(), nullable=True),
    sa.Column('estimated_damage_cost', sa.Numeric(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('follow_up_flags', sa.JSON(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corporation', 'event_id', 'row_id', name='uq_sitrep_incident_corp_event_row')
    )
    op.create_index(op.f('ix_sitrep_incidents_corporation'), 'sitrep_incidents', ['corporation'], unique=False)
    op.create_index(op.f('ix_sitrep_incidents_event_id'), 'sitrep_incidents', ['event_id'], unique=False)
    op.create_index(op.f('ix_sitrep_incidents_submission_id'), 'sitrep_incidents', ['submission_id'], unique=False)
    op.create_table('situation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('item', sa.String(), nullable=True),
    sa.Column('quantity', sa.Numeric(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_situation_logs_category'), 'situation_logs', ['category'], unique=False)
    op.create_index(op.f('ix_situation_logs_item'), 'situation_logs', ['item'], unique=False)
    op.create_index(op.f('ix_situation_logs_submission_id'), 'situation_logs', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_situation_logs_submission_id'), table_name='situation_logs')
    op.drop_index(op.f('ix_situation_logs_item'), table_name='situation_logs')
    op.drop_index(op.f('ix_situation_logs_category'), table_name='situation_logs')
    op.drop_table('situation_logs')
    op.drop_index(op.f('ix_sitrep_incidents_submission_id'), table_name='sitrep_incidents')
    op.drop_index(op.f('ix_sitrep_incidents_event_id'), table_name='sitrep_incidents')
    op.drop_index(op.f('ix_sitrep_incidents_corporation'), table_name='sitrep_incidents')
    op.drop_table('sitrep_incidents')
    op.drop_index(op.f('ix_capture_sessions_event_id'), table_name='capture_sessions')
    op.drop_index(op.f('ix_capture_sessions_corporation'), table_name='capture_sessions')
    op.drop_table('capture_sessions')
    op.drop_index(op.f('ix_submissions_event_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_corporation'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_as_at'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_table('whatsapp_drafts')
    op.drop_table('reports')
    op.drop_table('report_templates')
    op.drop_index(op.f('ix_field_observations_global_id'), table_name='field_observations')
    op.drop_index(op.f('ix_field_observations_dedup_hash'), table_name='field_observations')
    op.drop_table('field_observations')
    op.drop_index(op.f('ix_events_corporation'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
