"""create incidents table

Revision ID: 5ca6cf76e503
Revises: 
Create Date: 2026-07-14 23:20:05.964518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ca6cf76e503'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_id', sa.String(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('corporation', sa.String(), nullable=True),
    sa.Column('raw_corporation', sa.String(), nullable=True),
    sa.Column('community', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('incident_type', sa.String(), nullable=True),
    sa.Column('raw_incident_type', sa.String(), nullable=True),
    sa.Column('incident_type_other', sa.String(), nullable=True),
    sa.Column('incident_summary', sa.Text(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('event_time', sa.String(), nullable=True),
    sa.Column('assessment_date', sa.DateTime(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('edit_date', sa.DateTime(), nullable=True),
    sa.Column('occupants_count', sa.Integer(), nullable=True),
    sa.Column('injuries_occurred', sa.Boolean(), nullable=False),
    sa.Column('injuries_count', sa.Integer(), nullable=True),
    sa.Column('deaths_occurred', sa.Boolean(), nullable=False),
    sa.Column('deaths_count', sa.Integer(), nullable=True),
    sa.Column('building_damage', sa.Text(), nullable=True),
    sa.Column('crops_livestock', sa.Text(), nullable=True),
    sa.Column('personal_items', sa.Text(), nullable=True),
    sa.Column('furniture_appliances', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.String(), nullable=True),
    sa.Column('relief_items', sa.Text(), nullable=True),
    sa.Column('shelter', sa.Text(), nullable=True),
    sa.Column('special_needs_occupants', sa.Integer(), nullable=True),
    sa.Column('estimated_damage_cost', sa.Numeric(), nullable=True),
    sa.Column('follow_up', sa.String(), nullable=True),
    sa.Column('follow_up_flags', sa.JSON(), nullable=False),
    sa.Column('validation_status', sa.String(), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('duplicate_reason', sa.String(), nullable=True),
    sa.Column('flood_type', sa.String(), nullable=True),
    sa.Column('flood_trigger', sa.String(), nullable=True),
    sa.Column('flood_height', sa.String(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('officer_name', sa.String(), nullable=True),
    sa.Column('officer_position', sa.String(), nullable=True),
    sa.Column('dedup_hash', sa.String(), nullable=True),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_dedup_hash'), 'incidents', ['dedup_hash'], unique=False)
    op.create_index(op.f('ix_incidents_global_id'), 'incidents', ['global_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_global_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_dedup_hash'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
