/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhoAreYouRouteImport } from './routes/who-are-you'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DmuIndexRouteImport } from './routes/dmu/index'
import { Route as CorpIndexRouteImport } from './routes/corp/index'
import { Route as DmuFieldDataRouteImport } from './routes/dmu/field-data'
import { Route as DmuReportsIndexRouteImport } from './routes/dmu/reports/index'
import { Route as DmuReportsNewRouteImport } from './routes/dmu/reports/new'
import { Route as DmuReportsReportIdRouteImport } from './routes/dmu/reports/$reportId'
import { Route as DmuAdminModulesRouteImport } from './routes/dmu/admin/modules'
import { Route as DmuAdminTemplatesIndexRouteImport } from './routes/dmu/admin/templates/index'
import { Route as DmuAdminTemplatesNameIndexRouteImport } from './routes/dmu/admin/templates/$name/index'
import { Route as DmuAdminTemplatesNameNewRouteImport } from './routes/dmu/admin/templates/$name/new'
import { Route as DmuAdminTemplatesNameVersionsVersionRouteImport } from './routes/dmu/admin/templates/$name/versions/$version'

const WhoAreYouRoute = WhoAreYouRouteImport.update({
  id: '/who-are-you',
  path: '/who-are-you',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DmuIndexRoute = DmuIndexRouteImport.update({
  id: '/dmu/',
  path: '/dmu/',
  getParentRoute: () => rootRouteImport,
} as any)
const CorpIndexRoute = CorpIndexRouteImport.update({
  id: '/corp/',
  path: '/corp/',
  getParentRoute: () => rootRouteImport,
} as any)
const DmuFieldDataRoute = DmuFieldDataRouteImport.update({
  id: '/dmu/field-data',
  path: '/dmu/field-data',
  getParentRoute: () => rootRouteImport,
} as any)
const DmuReportsIndexRoute = DmuReportsIndexRouteImport.update({
  id: '/dmu/reports/',
  path: '/dmu/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const DmuReportsNewRoute = DmuReportsNewRouteImport.update({
  id: '/dmu/reports/new',
  path: '/dmu/reports/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DmuReportsReportIdRoute = DmuReportsReportIdRouteImport.update({
  id: '/dmu/reports/$reportId',
  path: '/dmu/reports/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const DmuAdminModulesRoute = DmuAdminModulesRouteImport.update({
  id: '/dmu/admin/modules',
  path: '/dmu/admin/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const DmuAdminTemplatesIndexRoute = DmuAdminTemplatesIndexRouteImport.update({
  id: '/dmu/admin/templates/',
  path: '/dmu/admin/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const DmuAdminTemplatesNameIndexRoute =
  DmuAdminTemplatesNameIndexRouteImport.update({
    id: '/dmu/admin/templates/$name/',
    path: '/dmu/admin/templates/$name/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DmuAdminTemplatesNameNewRoute =
  DmuAdminTemplatesNameNewRouteImport.update({
    id: '/dmu/admin/templates/$name/new',
    path: '/dmu/admin/templates/$name/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const DmuAdminTemplatesNameVersionsVersionRoute =
  DmuAdminTemplatesNameVersionsVersionRouteImport.update({
    id: '/dmu/admin/templates/$name/versions/$version',
    path: '/dmu/admin/templates/$name/versions/$version',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/who-are-you': typeof WhoAreYouRoute
  '/dmu/field-data': typeof DmuFieldDataRoute
  '/corp/': typeof CorpIndexRoute
  '/dmu/': typeof DmuIndexRoute
  '/dmu/admin/modules': typeof DmuAdminModulesRoute
  '/dmu/reports/$reportId': typeof DmuReportsReportIdRoute
  '/dmu/reports/new': typeof DmuReportsNewRoute
  '/dmu/reports/': typeof DmuReportsIndexRoute
  '/dmu/admin/templates/': typeof DmuAdminTemplatesIndexRoute
  '/dmu/admin/templates/$name/new': typeof DmuAdminTemplatesNameNewRoute
  '/dmu/admin/templates/$name/': typeof DmuAdminTemplatesNameIndexRoute
  '/dmu/admin/templates/$name/versions/$version': typeof DmuAdminTemplatesNameVersionsVersionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/who-are-you': typeof WhoAreYouRoute
  '/dmu/field-data': typeof DmuFieldDataRoute
  '/corp': typeof CorpIndexRoute
  '/dmu': typeof DmuIndexRoute
  '/dmu/admin/modules': typeof DmuAdminModulesRoute
  '/dmu/reports/$reportId': typeof DmuReportsReportIdRoute
  '/dmu/reports/new': typeof DmuReportsNewRoute
  '/dmu/reports': typeof DmuReportsIndexRoute
  '/dmu/admin/templates': typeof DmuAdminTemplatesIndexRoute
  '/dmu/admin/templates/$name/new': typeof DmuAdminTemplatesNameNewRoute
  '/dmu/admin/templates/$name': typeof DmuAdminTemplatesNameIndexRoute
  '/dmu/admin/templates/$name/versions/$version': typeof DmuAdminTemplatesNameVersionsVersionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/who-are-you': typeof WhoAreYouRoute
  '/dmu/field-data': typeof DmuFieldDataRoute
  '/corp/': typeof CorpIndexRoute
  '/dmu/': typeof DmuIndexRoute
  '/dmu/admin/modules': typeof DmuAdminModulesRoute
  '/dmu/reports/$reportId': typeof DmuReportsReportIdRoute
  '/dmu/reports/new': typeof DmuReportsNewRoute
  '/dmu/reports/': typeof DmuReportsIndexRoute
  '/dmu/admin/templates/': typeof DmuAdminTemplatesIndexRoute
  '/dmu/admin/templates/$name/new': typeof DmuAdminTemplatesNameNewRoute
  '/dmu/admin/templates/$name/': typeof DmuAdminTemplatesNameIndexRoute
  '/dmu/admin/templates/$name/versions/$version': typeof DmuAdminTemplatesNameVersionsVersionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/who-are-you'
    | '/dmu/field-data'
    | '/corp/'
    | '/dmu/'
    | '/dmu/admin/modules'
    | '/dmu/reports/$reportId'
    | '/dmu/reports/new'
    | '/dmu/reports/'
    | '/dmu/admin/templates/'
    | '/dmu/admin/templates/$name/new'
    | '/dmu/admin/templates/$name/'
    | '/dmu/admin/templates/$name/versions/$version'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/who-are-you'
    | '/dmu/field-data'
    | '/corp'
    | '/dmu'
    | '/dmu/admin/modules'
    | '/dmu/reports/$reportId'
    | '/dmu/reports/new'
    | '/dmu/reports'
    | '/dmu/admin/templates'
    | '/dmu/admin/templates/$name/new'
    | '/dmu/admin/templates/$name'
    | '/dmu/admin/templates/$name/versions/$version'
  id:
    | '__root__'
    | '/'
    | '/who-are-you'
    | '/dmu/field-data'
    | '/corp/'
    | '/dmu/'
    | '/dmu/admin/modules'
    | '/dmu/reports/$reportId'
    | '/dmu/reports/new'
    | '/dmu/reports/'
    | '/dmu/admin/templates/'
    | '/dmu/admin/templates/$name/new'
    | '/dmu/admin/templates/$name/'
    | '/dmu/admin/templates/$name/versions/$version'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WhoAreYouRoute: typeof WhoAreYouRoute
  DmuFieldDataRoute: typeof DmuFieldDataRoute
  CorpIndexRoute: typeof CorpIndexRoute
  DmuIndexRoute: typeof DmuIndexRoute
  DmuAdminModulesRoute: typeof DmuAdminModulesRoute
  DmuReportsReportIdRoute: typeof DmuReportsReportIdRoute
  DmuReportsNewRoute: typeof DmuReportsNewRoute
  DmuReportsIndexRoute: typeof DmuReportsIndexRoute
  DmuAdminTemplatesIndexRoute: typeof DmuAdminTemplatesIndexRoute
  DmuAdminTemplatesNameNewRoute: typeof DmuAdminTemplatesNameNewRoute
  DmuAdminTemplatesNameIndexRoute: typeof DmuAdminTemplatesNameIndexRoute
  DmuAdminTemplatesNameVersionsVersionRoute: typeof DmuAdminTemplatesNameVersionsVersionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/who-are-you': {
      id: '/who-are-you'
      path: '/who-are-you'
      fullPath: '/who-are-you'
      preLoaderRoute: typeof WhoAreYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmu/': {
      id: '/dmu/'
      path: '/dmu'
      fullPath: '/dmu/'
      preLoaderRoute: typeof DmuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corp/': {
      id: '/corp/'
      path: '/corp'
      fullPath: '/corp/'
      preLoaderRoute: typeof CorpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmu/field-data': {
      id: '/dmu/field-data'
      path: '/dmu/field-data'
      fullPath: '/dmu/field-data'
      preLoaderRoute: typeof DmuFieldDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmu/reports/': {
      id: '/dmu/reports/'
      path: '/dmu/reports'
      fullPath: '/dmu/reports/'
      preLoaderRoute: typeof DmuReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmu/reports/new': {
      id: '/dmu/reports/new'
      path: '/dmu/reports/new'
      fullPath: '/dmu/reports/new'
      preLoaderRoute: typeof DmuReportsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmu/reports/$reportId': {
      id: '/dmu/reports/$reportId'
      path: '/dmu/reports/$reportId'
      fullPath: '/dmu/reports/$reportId'
      preLoaderRoute: typeof DmuReportsReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmu/admin/modules': {
      id: '/dmu/admin/modules'
      path: '/dmu/admin/modules'
      fullPath: '/dmu/admin/modules'
      preLoaderRoute: typeof DmuAdminModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmu/admin/templates/': {
      id: '/dmu/admin/templates/'
      path: '/dmu/admin/templates'
      fullPath: '/dmu/admin/templates/'
      preLoaderRoute: typeof DmuAdminTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmu/admin/templates/$name/': {
      id: '/dmu/admin/templates/$name/'
      path: '/dmu/admin/templates/$name'
      fullPath: '/dmu/admin/templates/$name/'
      preLoaderRoute: typeof DmuAdminTemplatesNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmu/admin/templates/$name/new': {
      id: '/dmu/admin/templates/$name/new'
      path: '/dmu/admin/templates/$name/new'
      fullPath: '/dmu/admin/templates/$name/new'
      preLoaderRoute: typeof DmuAdminTemplatesNameNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmu/admin/templates/$name/versions/$version': {
      id: '/dmu/admin/templates/$name/versions/$version'
      path: '/dmu/admin/templates/$name/versions/$version'
      fullPath: '/dmu/admin/templates/$name/versions/$version'
      preLoaderRoute: typeof DmuAdminTemplatesNameVersionsVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WhoAreYouRoute: WhoAreYouRoute,
  DmuFieldDataRoute: DmuFieldDataRoute,
  CorpIndexRoute: CorpIndexRoute,
  DmuIndexRoute: DmuIndexRoute,
  DmuAdminModulesRoute: DmuAdminModulesRoute,
  DmuReportsReportIdRoute: DmuReportsReportIdRoute,
  DmuReportsNewRoute: DmuReportsNewRoute,
  DmuReportsIndexRoute: DmuReportsIndexRoute,
  DmuAdminTemplatesIndexRoute: DmuAdminTemplatesIndexRoute,
  DmuAdminTemplatesNameNewRoute: DmuAdminTemplatesNameNewRoute,
  DmuAdminTemplatesNameIndexRoute: DmuAdminTemplatesNameIndexRoute,
  DmuAdminTemplatesNameVersionsVersionRoute:
    DmuAdminTemplatesNameVersionsVersionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
