/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhoAreYouRouteImport } from './routes/who-are-you'
import { Route as SystemUnavailableRouteImport } from './routes/system-unavailable'
import { Route as DmuRouteImport } from './routes/dmu'
import { Route as CorpRouteImport } from './routes/corp'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DmuIndexRouteImport } from './routes/dmu/index'
import { Route as CorpIndexRouteImport } from './routes/corp/index'
import { Route as DmuWhatsappRouteImport } from './routes/dmu/whatsapp'
import { Route as DmuFieldDataRouteImport } from './routes/dmu/field-data'
import { Route as AuthVerifyRouteImport } from './routes/_auth/verify'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as DmuReportsIndexRouteImport } from './routes/dmu/reports/index'
import { Route as DmuReportsNewRouteImport } from './routes/dmu/reports/new'
import { Route as DmuReportsReportIdRouteImport } from './routes/dmu/reports/$reportId'
import { Route as DmuCorporationsCorporationRouteImport } from './routes/dmu/corporations/$corporation'
import { Route as DmuAdminModulesRouteImport } from './routes/dmu/admin/modules'
import { Route as CorpPrintSessionIdRouteImport } from './routes/corp/print.$sessionId'
import { Route as CorpFilingsSubmissionIdRouteImport } from './routes/corp/filings/$submissionId'
import { Route as CorpCSessionIdRouteImport } from './routes/corp/c/$sessionId'
import { Route as DmuAdminTemplatesIndexRouteImport } from './routes/dmu/admin/templates/index'
import { Route as CorpEventsEventIdIndexRouteImport } from './routes/corp/events/$eventId/index'
import { Route as DmuAdminTemplatesNameIndexRouteImport } from './routes/dmu/admin/templates/$name/index'
import { Route as DmuAdminTemplatesNameNewRouteImport } from './routes/dmu/admin/templates/$name/new'
import { Route as DmuAdminTemplatesNameVersionsVersionRouteImport } from './routes/dmu/admin/templates/$name/versions/$version'

const WhoAreYouRoute = WhoAreYouRouteImport.update({
  id: '/who-are-you',
  path: '/who-are-you',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemUnavailableRoute = SystemUnavailableRouteImport.update({
  id: '/system-unavailable',
  path: '/system-unavailable',
  getParentRoute: () => rootRouteImport,
} as any)
const DmuRoute = DmuRouteImport.update({
  id: '/dmu',
  path: '/dmu',
  getParentRoute: () => rootRouteImport,
} as any)
const CorpRoute = CorpRouteImport.update({
  id: '/corp',
  path: '/corp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DmuIndexRoute = DmuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DmuRoute,
} as any)
const CorpIndexRoute = CorpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CorpRoute,
} as any)
const DmuWhatsappRoute = DmuWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => DmuRoute,
} as any)
const DmuFieldDataRoute = DmuFieldDataRouteImport.update({
  id: '/field-data',
  path: '/field-data',
  getParentRoute: () => DmuRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const DmuReportsIndexRoute = DmuReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => DmuRoute,
} as any)
const DmuReportsNewRoute = DmuReportsNewRouteImport.update({
  id: '/reports/new',
  path: '/reports/new',
  getParentRoute: () => DmuRoute,
} as any)
const DmuReportsReportIdRoute = DmuReportsReportIdRouteImport.update({
  id: '/reports/$reportId',
  path: '/reports/$reportId',
  getParentRoute: () => DmuRoute,
} as any)
const DmuCorporationsCorporationRoute =
  DmuCorporationsCorporationRouteImport.update({
    id: '/corporations/$corporation',
    path: '/corporations/$corporation',
    getParentRoute: () => DmuRoute,
  } as any)
const DmuAdminModulesRoute = DmuAdminModulesRouteImport.update({
  id: '/admin/modules',
  path: '/admin/modules',
  getParentRoute: () => DmuRoute,
} as any)
const CorpPrintSessionIdRoute = CorpPrintSessionIdRouteImport.update({
  id: '/print/$sessionId',
  path: '/print/$sessionId',
  getParentRoute: () => CorpRoute,
} as any)
const CorpFilingsSubmissionIdRoute = CorpFilingsSubmissionIdRouteImport.update({
  id: '/filings/$submissionId',
  path: '/filings/$submissionId',
  getParentRoute: () => CorpRoute,
} as any)
const CorpCSessionIdRoute = CorpCSessionIdRouteImport.update({
  id: '/c/$sessionId',
  path: '/c/$sessionId',
  getParentRoute: () => CorpRoute,
} as any)
const DmuAdminTemplatesIndexRoute = DmuAdminTemplatesIndexRouteImport.update({
  id: '/admin/templates/',
  path: '/admin/templates/',
  getParentRoute: () => DmuRoute,
} as any)
const CorpEventsEventIdIndexRoute = CorpEventsEventIdIndexRouteImport.update({
  id: '/events/$eventId/',
  path: '/events/$eventId/',
  getParentRoute: () => CorpRoute,
} as any)
const DmuAdminTemplatesNameIndexRoute =
  DmuAdminTemplatesNameIndexRouteImport.update({
    id: '/admin/templates/$name/',
    path: '/admin/templates/$name/',
    getParentRoute: () => DmuRoute,
  } as any)
const DmuAdminTemplatesNameNewRoute =
  DmuAdminTemplatesNameNewRouteImport.update({
    id: '/admin/templates/$name/new',
    path: '/admin/templates/$name/new',
    getParentRoute: () => DmuRoute,
  } as any)
const DmuAdminTemplatesNameVersionsVersionRoute =
  DmuAdminTemplatesNameVersionsVersionRouteImport.update({
    id: '/admin/templates/$name/versions/$version',
    path: '/admin/templates/$name/versions/$version',
    getParentRoute: () => DmuRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/corp': typeof CorpRouteWithChildren
  '/dmu': typeof DmuRouteWithChildren
  '/system-unavailable': typeof SystemUnavailableRoute
  '/who-are-you': typeof WhoAreYouRoute
  '/login': typeof AuthLoginRoute
  '/verify': typeof AuthVerifyRoute
  '/dmu/field-data': typeof DmuFieldDataRoute
  '/dmu/whatsapp': typeof DmuWhatsappRoute
  '/corp/': typeof CorpIndexRoute
  '/dmu/': typeof DmuIndexRoute
  '/corp/c/$sessionId': typeof CorpCSessionIdRoute
  '/corp/filings/$submissionId': typeof CorpFilingsSubmissionIdRoute
  '/corp/print/$sessionId': typeof CorpPrintSessionIdRoute
  '/dmu/admin/modules': typeof DmuAdminModulesRoute
  '/dmu/corporations/$corporation': typeof DmuCorporationsCorporationRoute
  '/dmu/reports/$reportId': typeof DmuReportsReportIdRoute
  '/dmu/reports/new': typeof DmuReportsNewRoute
  '/dmu/reports/': typeof DmuReportsIndexRoute
  '/corp/events/$eventId/': typeof CorpEventsEventIdIndexRoute
  '/dmu/admin/templates/': typeof DmuAdminTemplatesIndexRoute
  '/dmu/admin/templates/$name/new': typeof DmuAdminTemplatesNameNewRoute
  '/dmu/admin/templates/$name/': typeof DmuAdminTemplatesNameIndexRoute
  '/dmu/admin/templates/$name/versions/$version': typeof DmuAdminTemplatesNameVersionsVersionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/system-unavailable': typeof SystemUnavailableRoute
  '/who-are-you': typeof WhoAreYouRoute
  '/login': typeof AuthLoginRoute
  '/verify': typeof AuthVerifyRoute
  '/dmu/field-data': typeof DmuFieldDataRoute
  '/dmu/whatsapp': typeof DmuWhatsappRoute
  '/corp': typeof CorpIndexRoute
  '/dmu': typeof DmuIndexRoute
  '/corp/c/$sessionId': typeof CorpCSessionIdRoute
  '/corp/filings/$submissionId': typeof CorpFilingsSubmissionIdRoute
  '/corp/print/$sessionId': typeof CorpPrintSessionIdRoute
  '/dmu/admin/modules': typeof DmuAdminModulesRoute
  '/dmu/corporations/$corporation': typeof DmuCorporationsCorporationRoute
  '/dmu/reports/$reportId': typeof DmuReportsReportIdRoute
  '/dmu/reports/new': typeof DmuReportsNewRoute
  '/dmu/reports': typeof DmuReportsIndexRoute
  '/corp/events/$eventId': typeof CorpEventsEventIdIndexRoute
  '/dmu/admin/templates': typeof DmuAdminTemplatesIndexRoute
  '/dmu/admin/templates/$name/new': typeof DmuAdminTemplatesNameNewRoute
  '/dmu/admin/templates/$name': typeof DmuAdminTemplatesNameIndexRoute
  '/dmu/admin/templates/$name/versions/$version': typeof DmuAdminTemplatesNameVersionsVersionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/corp': typeof CorpRouteWithChildren
  '/dmu': typeof DmuRouteWithChildren
  '/system-unavailable': typeof SystemUnavailableRoute
  '/who-are-you': typeof WhoAreYouRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/verify': typeof AuthVerifyRoute
  '/dmu/field-data': typeof DmuFieldDataRoute
  '/dmu/whatsapp': typeof DmuWhatsappRoute
  '/corp/': typeof CorpIndexRoute
  '/dmu/': typeof DmuIndexRoute
  '/corp/c/$sessionId': typeof CorpCSessionIdRoute
  '/corp/filings/$submissionId': typeof CorpFilingsSubmissionIdRoute
  '/corp/print/$sessionId': typeof CorpPrintSessionIdRoute
  '/dmu/admin/modules': typeof DmuAdminModulesRoute
  '/dmu/corporations/$corporation': typeof DmuCorporationsCorporationRoute
  '/dmu/reports/$reportId': typeof DmuReportsReportIdRoute
  '/dmu/reports/new': typeof DmuReportsNewRoute
  '/dmu/reports/': typeof DmuReportsIndexRoute
  '/corp/events/$eventId/': typeof CorpEventsEventIdIndexRoute
  '/dmu/admin/templates/': typeof DmuAdminTemplatesIndexRoute
  '/dmu/admin/templates/$name/new': typeof DmuAdminTemplatesNameNewRoute
  '/dmu/admin/templates/$name/': typeof DmuAdminTemplatesNameIndexRoute
  '/dmu/admin/templates/$name/versions/$version': typeof DmuAdminTemplatesNameVersionsVersionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/corp'
    | '/dmu'
    | '/system-unavailable'
    | '/who-are-you'
    | '/login'
    | '/verify'
    | '/dmu/field-data'
    | '/dmu/whatsapp'
    | '/corp/'
    | '/dmu/'
    | '/corp/c/$sessionId'
    | '/corp/filings/$submissionId'
    | '/corp/print/$sessionId'
    | '/dmu/admin/modules'
    | '/dmu/corporations/$corporation'
    | '/dmu/reports/$reportId'
    | '/dmu/reports/new'
    | '/dmu/reports/'
    | '/corp/events/$eventId/'
    | '/dmu/admin/templates/'
    | '/dmu/admin/templates/$name/new'
    | '/dmu/admin/templates/$name/'
    | '/dmu/admin/templates/$name/versions/$version'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/system-unavailable'
    | '/who-are-you'
    | '/login'
    | '/verify'
    | '/dmu/field-data'
    | '/dmu/whatsapp'
    | '/corp'
    | '/dmu'
    | '/corp/c/$sessionId'
    | '/corp/filings/$submissionId'
    | '/corp/print/$sessionId'
    | '/dmu/admin/modules'
    | '/dmu/corporations/$corporation'
    | '/dmu/reports/$reportId'
    | '/dmu/reports/new'
    | '/dmu/reports'
    | '/corp/events/$eventId'
    | '/dmu/admin/templates'
    | '/dmu/admin/templates/$name/new'
    | '/dmu/admin/templates/$name'
    | '/dmu/admin/templates/$name/versions/$version'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/corp'
    | '/dmu'
    | '/system-unavailable'
    | '/who-are-you'
    | '/_auth/login'
    | '/_auth/verify'
    | '/dmu/field-data'
    | '/dmu/whatsapp'
    | '/corp/'
    | '/dmu/'
    | '/corp/c/$sessionId'
    | '/corp/filings/$submissionId'
    | '/corp/print/$sessionId'
    | '/dmu/admin/modules'
    | '/dmu/corporations/$corporation'
    | '/dmu/reports/$reportId'
    | '/dmu/reports/new'
    | '/dmu/reports/'
    | '/corp/events/$eventId/'
    | '/dmu/admin/templates/'
    | '/dmu/admin/templates/$name/new'
    | '/dmu/admin/templates/$name/'
    | '/dmu/admin/templates/$name/versions/$version'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  CorpRoute: typeof CorpRouteWithChildren
  DmuRoute: typeof DmuRouteWithChildren
  SystemUnavailableRoute: typeof SystemUnavailableRoute
  WhoAreYouRoute: typeof WhoAreYouRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/who-are-you': {
      id: '/who-are-you'
      path: '/who-are-you'
      fullPath: '/who-are-you'
      preLoaderRoute: typeof WhoAreYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-unavailable': {
      id: '/system-unavailable'
      path: '/system-unavailable'
      fullPath: '/system-unavailable'
      preLoaderRoute: typeof SystemUnavailableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmu': {
      id: '/dmu'
      path: '/dmu'
      fullPath: '/dmu'
      preLoaderRoute: typeof DmuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corp': {
      id: '/corp'
      path: '/corp'
      fullPath: '/corp'
      preLoaderRoute: typeof CorpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmu/': {
      id: '/dmu/'
      path: '/'
      fullPath: '/dmu/'
      preLoaderRoute: typeof DmuIndexRouteImport
      parentRoute: typeof DmuRoute
    }
    '/corp/': {
      id: '/corp/'
      path: '/'
      fullPath: '/corp/'
      preLoaderRoute: typeof CorpIndexRouteImport
      parentRoute: typeof CorpRoute
    }
    '/dmu/whatsapp': {
      id: '/dmu/whatsapp'
      path: '/whatsapp'
      fullPath: '/dmu/whatsapp'
      preLoaderRoute: typeof DmuWhatsappRouteImport
      parentRoute: typeof DmuRoute
    }
    '/dmu/field-data': {
      id: '/dmu/field-data'
      path: '/field-data'
      fullPath: '/dmu/field-data'
      preLoaderRoute: typeof DmuFieldDataRouteImport
      parentRoute: typeof DmuRoute
    }
    '/_auth/verify': {
      id: '/_auth/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/dmu/reports/': {
      id: '/dmu/reports/'
      path: '/reports'
      fullPath: '/dmu/reports/'
      preLoaderRoute: typeof DmuReportsIndexRouteImport
      parentRoute: typeof DmuRoute
    }
    '/dmu/reports/new': {
      id: '/dmu/reports/new'
      path: '/reports/new'
      fullPath: '/dmu/reports/new'
      preLoaderRoute: typeof DmuReportsNewRouteImport
      parentRoute: typeof DmuRoute
    }
    '/dmu/reports/$reportId': {
      id: '/dmu/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/dmu/reports/$reportId'
      preLoaderRoute: typeof DmuReportsReportIdRouteImport
      parentRoute: typeof DmuRoute
    }
    '/dmu/corporations/$corporation': {
      id: '/dmu/corporations/$corporation'
      path: '/corporations/$corporation'
      fullPath: '/dmu/corporations/$corporation'
      preLoaderRoute: typeof DmuCorporationsCorporationRouteImport
      parentRoute: typeof DmuRoute
    }
    '/dmu/admin/modules': {
      id: '/dmu/admin/modules'
      path: '/admin/modules'
      fullPath: '/dmu/admin/modules'
      preLoaderRoute: typeof DmuAdminModulesRouteImport
      parentRoute: typeof DmuRoute
    }
    '/corp/print/$sessionId': {
      id: '/corp/print/$sessionId'
      path: '/print/$sessionId'
      fullPath: '/corp/print/$sessionId'
      preLoaderRoute: typeof CorpPrintSessionIdRouteImport
      parentRoute: typeof CorpRoute
    }
    '/corp/filings/$submissionId': {
      id: '/corp/filings/$submissionId'
      path: '/filings/$submissionId'
      fullPath: '/corp/filings/$submissionId'
      preLoaderRoute: typeof CorpFilingsSubmissionIdRouteImport
      parentRoute: typeof CorpRoute
    }
    '/corp/c/$sessionId': {
      id: '/corp/c/$sessionId'
      path: '/c/$sessionId'
      fullPath: '/corp/c/$sessionId'
      preLoaderRoute: typeof CorpCSessionIdRouteImport
      parentRoute: typeof CorpRoute
    }
    '/dmu/admin/templates/': {
      id: '/dmu/admin/templates/'
      path: '/admin/templates'
      fullPath: '/dmu/admin/templates/'
      preLoaderRoute: typeof DmuAdminTemplatesIndexRouteImport
      parentRoute: typeof DmuRoute
    }
    '/corp/events/$eventId/': {
      id: '/corp/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/corp/events/$eventId/'
      preLoaderRoute: typeof CorpEventsEventIdIndexRouteImport
      parentRoute: typeof CorpRoute
    }
    '/dmu/admin/templates/$name/': {
      id: '/dmu/admin/templates/$name/'
      path: '/admin/templates/$name'
      fullPath: '/dmu/admin/templates/$name/'
      preLoaderRoute: typeof DmuAdminTemplatesNameIndexRouteImport
      parentRoute: typeof DmuRoute
    }
    '/dmu/admin/templates/$name/new': {
      id: '/dmu/admin/templates/$name/new'
      path: '/admin/templates/$name/new'
      fullPath: '/dmu/admin/templates/$name/new'
      preLoaderRoute: typeof DmuAdminTemplatesNameNewRouteImport
      parentRoute: typeof DmuRoute
    }
    '/dmu/admin/templates/$name/versions/$version': {
      id: '/dmu/admin/templates/$name/versions/$version'
      path: '/admin/templates/$name/versions/$version'
      fullPath: '/dmu/admin/templates/$name/versions/$version'
      preLoaderRoute: typeof DmuAdminTemplatesNameVersionsVersionRouteImport
      parentRoute: typeof DmuRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface CorpRouteChildren {
  CorpIndexRoute: typeof CorpIndexRoute
  CorpCSessionIdRoute: typeof CorpCSessionIdRoute
  CorpFilingsSubmissionIdRoute: typeof CorpFilingsSubmissionIdRoute
  CorpPrintSessionIdRoute: typeof CorpPrintSessionIdRoute
  CorpEventsEventIdIndexRoute: typeof CorpEventsEventIdIndexRoute
}

const CorpRouteChildren: CorpRouteChildren = {
  CorpIndexRoute: CorpIndexRoute,
  CorpCSessionIdRoute: CorpCSessionIdRoute,
  CorpFilingsSubmissionIdRoute: CorpFilingsSubmissionIdRoute,
  CorpPrintSessionIdRoute: CorpPrintSessionIdRoute,
  CorpEventsEventIdIndexRoute: CorpEventsEventIdIndexRoute,
}

const CorpRouteWithChildren = CorpRoute._addFileChildren(CorpRouteChildren)

interface DmuRouteChildren {
  DmuFieldDataRoute: typeof DmuFieldDataRoute
  DmuWhatsappRoute: typeof DmuWhatsappRoute
  DmuIndexRoute: typeof DmuIndexRoute
  DmuAdminModulesRoute: typeof DmuAdminModulesRoute
  DmuCorporationsCorporationRoute: typeof DmuCorporationsCorporationRoute
  DmuReportsReportIdRoute: typeof DmuReportsReportIdRoute
  DmuReportsNewRoute: typeof DmuReportsNewRoute
  DmuReportsIndexRoute: typeof DmuReportsIndexRoute
  DmuAdminTemplatesIndexRoute: typeof DmuAdminTemplatesIndexRoute
  DmuAdminTemplatesNameNewRoute: typeof DmuAdminTemplatesNameNewRoute
  DmuAdminTemplatesNameIndexRoute: typeof DmuAdminTemplatesNameIndexRoute
  DmuAdminTemplatesNameVersionsVersionRoute: typeof DmuAdminTemplatesNameVersionsVersionRoute
}

const DmuRouteChildren: DmuRouteChildren = {
  DmuFieldDataRoute: DmuFieldDataRoute,
  DmuWhatsappRoute: DmuWhatsappRoute,
  DmuIndexRoute: DmuIndexRoute,
  DmuAdminModulesRoute: DmuAdminModulesRoute,
  DmuCorporationsCorporationRoute: DmuCorporationsCorporationRoute,
  DmuReportsReportIdRoute: DmuReportsReportIdRoute,
  DmuReportsNewRoute: DmuReportsNewRoute,
  DmuReportsIndexRoute: DmuReportsIndexRoute,
  DmuAdminTemplatesIndexRoute: DmuAdminTemplatesIndexRoute,
  DmuAdminTemplatesNameNewRoute: DmuAdminTemplatesNameNewRoute,
  DmuAdminTemplatesNameIndexRoute: DmuAdminTemplatesNameIndexRoute,
  DmuAdminTemplatesNameVersionsVersionRoute:
    DmuAdminTemplatesNameVersionsVersionRoute,
}

const DmuRouteWithChildren = DmuRoute._addFileChildren(DmuRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  CorpRoute: CorpRouteWithChildren,
  DmuRoute: DmuRouteWithChildren,
  SystemUnavailableRoute: SystemUnavailableRoute,
  WhoAreYouRoute: WhoAreYouRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
